name: Run SonarScanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_sonarscanner:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull vighneshak/sonar-scanner-dotnet:latest

    - name: Run SonarScanner begin
      run: |
        docker run --rm \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v "${{ github.workspace }}:/app" \
          -w /app \
          vighneshak/sonar-scanner-dotnet:latest \
          begin /k:"your_project_key" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }}

    - name: Run SonarScanner end
      run: |
        docker run --rm \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v "${{ github.workspace }}:/app" \
          -w /app \
          vighneshak/sonar-scanner-dotnet:latest \
          end /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }}
