name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-sonar-scanner-image .

      - name: Run Docker container interactively
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          docker run -it --rm \
            -e SONAR_HOST_URL=$SONAR_HOST_URL \
            -e SONAR_TOKEN=$SONAR_TOKEN \
            -v "$(pwd):/app" \
            --entrypoint /bin/sh \
            my-sonar-scanner-image

      - name: Verify directory structure
        run: |
          ls -la /app
