name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarQube scanner using Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=$SONAR_HOST_URL \
            -e SONAR_TOKEN=$SONAR_TOKEN \
            -v "$(pwd):/app" \
            vighneshak/sonar-scanner-dotnet \
            bash -c "dotnet-sonarscanner begin /k:\"dot-net-test\" /d:sonar.host.url=\"$SONAR_HOST_URL\" /d:sonar.login=\"$SONAR_TOKEN\" /d:sonar.exclusions=\"**/node_modules/**\" && dotnet build && dotnet-sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
