name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Pull Docker image
        run: docker pull vighneshak/sonar-scanner-dotnet:latest

      - name: Change entrypoint script permissions
        run: docker run --rm -v "${{ github.workspace }}:/src" vighneshak/sonar-scanner-dotnet:latest chmod +x /entrypoint.sh

      - name: Run SonarQube scanner in Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          INPUT_SONARHOSTNAME: ${{ secrets.SONAR_HOST_URL }}
          INPUT_SONARPROJECTKEY: ".net-test"
          INPUT_SONARPROJECTNAME: ".net-test"
          INPUT_DOTNETBUILDARGUMENTS: ""  # Any build arguments, if needed
          INPUT_SONARBEGINARGUMENTS: ""  # Any additional arguments for the begin step
        run: |
          docker run --rm \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -e INPUT_SONARHOSTNAME="${{ secrets.SONAR_HOST_URL }}" \
            -e INPUT_SONARPROJECTKEY=".net-test" \
            -e INPUT_SONARPROJECTNAME=".net-test" \
            -e INPUT_DOTNETBUILDARGUMENTS="" \
            -e INPUT_SONARBEGINARGUMENTS="" \
            -v "${{ github.workspace }}:/src" vighneshak/sonar-scanner-dotnet:latest \
            /entrypoint.sh

