name: SonarScanner for .NET 8 with pull request decoration support

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-sonarscan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarScanner in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
                        -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
                        -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                        -e SONAR_PROJECT_KEY=${{ ".net-test"  }} \
                        -e SONAR_PROJECT_NAME=${{ ".net-test"  }} \
                        -e SONAR_HOSTNAME=${{ secrets.SONAR_HOSTNAME }} \
                        highbyte/sonarscan-dotnet:latest \
                        /bin/bash -c "cd /workspace && ./entrypoint.sh"
