name: Build, Push, and Run Docker Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/sonar-scanner-dotnet:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sonar-scanner-dotnet:latest

  run_container:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Run Docker container
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/sonar-scanner-dotnet:latest
        docker run --rm \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          ${{ secrets.DOCKER_HUB_USERNAME }}/sonar-scanner-dotnet:latest
